### ISSUE TITLE
Persistant components between bot restarts

### ISSUE THREAD

**Issue by Lunarmagpie** [HyperGH/hikari-miru#28]
### Summary

Miru should replace the current component persistence system to one thats easier to work with/possibly more efficient.
I believe a side effect of my implementation will also allow custom timeout responses for buttons.

### Why is this needed?

I think it is good if bots can still respond to a button after a restart.

### Ideal implementation

```python
# Internal
class ComponentInfo:
    """Info used to distinguish miru components from each other."""
    ....

# External
# The user is expected to implement these functions if they want to use persistence between restarts.

# Called when a component is created
@miru.persistence.save_component
async def save(nonce: str, component: miru.ComponentInfo) -> None:
    """Save a ComponentInfo object"""
    ...

# Called when a component nonce is received that isn't in the cachce
@miru.persistence.load_component
async def load(nonce: str) -> miru.ComponentInfo | None:
    """Load a ComponentInfo object. Return `None` if the object doesn't exist."""
    ...

# Called when 
@miru.persistence.delete_component
async def load(nonce: str) -> None:
    """Delete a component with a specific nonce."""
    ...
```

The internals will need to be reworked is have "registry/cache" with all the components. The nonce will be used to run the correct callback. This is similar to how crescent works so I can vouch for the system.

### Checklist

- [X] I have searched the issue tracker and have made sure it's not a duplicate. If it is a follow up of another issue, I have specified it.

**Comment by Lunarmagpie** [comment]
I think this is actually a much bigger change than I originally thought. May not be possible for this project.

**Comment by HyperGH** [comment]
> I think this is actually a much bigger change than I originally thought. May not be possible for this project.

As agreed, this may become it's own standalone component library in the future, closing for now.

**Comment by Lunarmagpie** [comment]
> > I think this is actually a much bigger change than I originally thought. May not be possible for this project.
> 
> As agreed, this may become it's own standalone component library in the future, closing for now.

stateless component lib when :trollface:
